name: Generate Changelog on Push

on:
  push:
    branches:
      - main # Or 'master', or any branch you want to trigger this on
    # You might still want to add paths filter if you only care about code changes
    # paths:
    #   - 'src/**'
    #   - 'package.json'
    #   - 'package-lock.json'

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required for conventional-changelog to work correctly
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a stable Node.js version suitable for your project

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog
        # This will always run and update CHANGELOG.md in place
        run: npm run changelog

      - name: Commit and Push Changelog (Always Attempt)
        # This step will run every time, potentially committing an unchanged file
        # if the 'Generate Changelog' step didn't actually change the content.
        # git commit will simply say "nothing to commit, working tree clean" in that case.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the changelog file. If it hasn't changed, 'git commit' will handle it.
          git add CHANGELOG.md
          
          # Use 'git commit --allow-empty' to create a commit even if no changes were staged,
          # or just let 'git commit' fail if there's nothing to commit.
          # For a more robust "only commit if truly changed" without the previous if condition,
          # you'd still need a check, but if your goal is to always try, this is it.
          # A simpler approach without the if condition that still only commits when needed:
          git commit -m "docs: auto-generate changelog [skip ci]" || echo "No changes to commit for changelog."
          
          # If a commit was made, push it.
          # This will only attempt a push if the previous commit command succeeded.
          # If 'git commit' said "nothing to commit", it won't proceed to push.
          git push || echo "No new changelog commit to push."
