name: Update Release note

on:
  release:
    types:
      - created # Trigger only when a new release is created
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

permissions:
  contents: write 
jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract latest changelog block
        id: changelog
        run: |
          awk '
            /^# / { if (p) exit; p=1 } p { print }
          ' CHANGELOG.md > latest_changelog.md

      - name: Update release body with gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "$GITHUB_REF_NAME" --notes-file latest_changelog.md

