name: Update Release Changelog

on:
  release:
    types: [created]

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract latest changelog block
        id: changelog
        run: |
          # Get first version block: from first '# ' to next '# ' or EOF
          awk '
            /^# / {
              if (p) exit; 
              p=1
            }
            p { print }
          ' CHANGELOG.md > latest_changelog.md

          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          cat latest_changelog.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update GitHub Release description
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.CHANGELOG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
