name: Update Release Changelog

on:
  release:
    types: [created]

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract latest changelog block
        id: changelog
        run: |
          awk '
            /^# / { if (p) exit; p=1 } p { print }
          ' CHANGELOG.md > latest_changelog.md

      - name: Update release body with gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "$GITHUB_REF_NAME" --notes-file latest_changelog.md

