name: Updating ECSDOT-Baremetal-repo

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Copy file to another repo manually
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          # Setup some variables
          COMMIT_USERNAME="zulaasim"
          DEST_USERNAME="zulaasim"
          COMMIT_EMAIL="zulaasim03@gmail.com"
          COMMIT_MESSAGE="hi"
          DEST_REPO="zulaasim/testing"
          DEST_BRANCH="main"
          DEST_DIR="projects/my-project"
          FILES="test.md"
          CLONE_DIRECTORY=$(mktemp -d)

          
          echo "##### Cloning source git repository #####"
          # Setup git
          git config --global user.email "$COMMIT_EMAIL"
          git config --global user.name "$COMMIT_USERNAME"
          
          # Remove git directory if it exists to prevent errors
          #maybe not needed
          #rm -rf .git
        
          
          echo "##### Cloning destination repo #####"
          git clone --single-branch --branch "$DEST_BRANCH" "https://x-access-token:${API_TOKEN_GITHUB}@github.com/${DEST_USERNAME}.git" "$CLONE_DIRECTORY"



          # Switch to the target branch (create if missing)
          # git checkout ${DEST_BRANCH} || git checkout -b ${DEST_BRANCH}

          echo "##### Copying contents to git repo #####"
          mkdir -p "$CLONE_DIRECTORY/$DEST_DIRECTORY"
          cp -rvf $SOURCE_FILES "$CLONE_DIRECTORY/$DEST_DIRECTORY"
          cd "$CLONE_DIRECTORY"

          # Commit and push
          git add .
          git commit -m "Update file from origin repo"
          git push origin ${DEST_BRANCH}

      
